package fr.chantapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TYPE_PAROLE".
 */
@Entity
public class TypeParole {

    @Id
    @Unique
    private long id;

    @NotNull
    private String libelleTypeParole;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public TypeParole() {
    }

    public TypeParole(long id) {
        this.id = id;
    }

    @Generated
    public TypeParole(long id, String libelleTypeParole) {
        this.id = id;
        this.libelleTypeParole = libelleTypeParole;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @NotNull
    public String getLibelleTypeParole() {
        return libelleTypeParole;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLibelleTypeParole(@NotNull String libelleTypeParole) {
        this.libelleTypeParole = libelleTypeParole;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
