package fr.chantapp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TYPE_PAROLE".
*/
public class TypeParoleDao extends AbstractDao<TypeParole, Long> {

    public static final String TABLENAME = "TYPE_PAROLE";

    /**
     * Properties of entity TypeParole.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property LibelleTypeParole = new Property(1, String.class, "libelleTypeParole", false, "LIBELLE_TYPE_PAROLE");
    }


    public TypeParoleDao(DaoConfig config) {
        super(config);
    }
    
    public TypeParoleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TYPE_PAROLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL UNIQUE ," + // 0: id
                "\"LIBELLE_TYPE_PAROLE\" TEXT NOT NULL );"); // 1: libelleTypeParole
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TYPE_PAROLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TypeParole entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getLibelleTypeParole());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TypeParole entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getLibelleTypeParole());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public TypeParole readEntity(Cursor cursor, int offset) {
        TypeParole entity = new TypeParole( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1) // libelleTypeParole
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TypeParole entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setLibelleTypeParole(cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TypeParole entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TypeParole entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TypeParole entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
